### ISSUE TITLE
Can't compile on Ubuntu 10.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RossBencina/oscpack#3]
```
What steps will reproduce the problem?
1. Download 1.0.2
2. run make

What version of the product are you using? On what operating system?
Using 1.0.2 on Ubuntu 10.10


Please provide any additional information below.
This is the output that I get after running make:

g++ -Wall -O3 -I./ -DOSC_HOST_LITTLE_ENDIAN   -c -o tests/OscUnitTests.o 
tests/OscUnitTests.cpp
tests/OscUnitTests.cpp: In function ‘void osc::assertEqual_(const T*, const 
T*, const char*, const char*, const char*, int) [with T = char]’:
tests/OscUnitTests.cpp:82: error: ‘strcmp’ was not declared in this scope
tests/OscUnitTests.cpp: In function ‘char* osc::NewMessageBuffer(const char*, 
long unsigned int)’:
tests/OscUnitTests.cpp:102: error: ‘memcpy’ was not declared in this scope
tests/OscUnitTests.cpp: In function ‘void osc::test1()’:
tests/OscUnitTests.cpp:116: error: ‘strcmp’ was not declared in this scope
tests/OscUnitTests.cpp: In function ‘void osc::test3()’:
tests/OscUnitTests.cpp:313: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:322: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:322: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:323: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:323: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:324: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:324: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:326: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:326: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:327: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:327: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:329: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:329: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:331: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:331: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:333: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:333: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:335: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:335: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:337: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:337: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:339: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:339: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:341: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:341: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:343: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:343: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:348: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:361: error: ‘memcmp’ was not declared in this scope
tests/OscUnitTests.cpp:365: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:365: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:367: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:367: error: ‘memset’ was not declared in this scope
tests/OscUnitTests.cpp:373: error: ‘memset’ was not declared in this scope
make: *** [tests/OscUnitTests.o] Error 1
```

Original issue reported on code.google.com by `bv3...@gmail.com` on 8 Mar 2011 at 11:46
