### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RossBencina/oscpack#2]
```
I can't compile with 1.0.1, 1.0.2 or with svn+cmake.

With svn/cmake I get:

cmake .

(ok)

oscpack/ make
Scanning dependencies of target OSC
[ 10%] Building CXX object CMakeFiles/OSC.dir/ip/IpEndpointName.cpp.o
[ 20%] Building CXX object CMakeFiles/OSC.dir/ip/posix/NetworkingUtils.cpp.o
[ 30%] Building CXX object CMakeFiles/OSC.dir/ip/posix/UdpSocket.cpp.o
[ 40%] Building CXX object CMakeFiles/OSC.dir/osc/OscPrintReceivedElements.cpp.o
[ 50%] Building CXX object CMakeFiles/OSC.dir/osc/OscReceivedElements.cpp.o
In file included from 
/home/smoge/teste/oscpack/osc/OscReceivedElements.cpp:34:0:
/home/smoge/teste/oscpack/osc/OscHostEndianness.h:70:2: error: #error please 
edit OSCHostEndianness.h to configure endianness
make[2]: ** [CMakeFiles/OSC.dir/osc/OscReceivedElements.cpp.o] Erro 1
make[1]: ** [CMakeFiles/OSC.dir/all] Erro 2
make: ** [all] Erro 2

What version of the product are you using? On what operating system?

ArchLinux (up to date)


```

Original issue reported on code.google.com by `bernardo...@gmail.com` on 1 Feb 2011 at 6:41
